MVCDoctoresCasa/Models/Doctor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace ApiDoctoresPruebaCasa.Models
{
    [Table("Doctor")]
    public class Doctor
    {
        [Column("HOSPITAL_COD")]
        public string Cod_Hospital { get; set; }
        [Key]
        [Column("DOCTOR_NO")]
        public string NumDoctor { get; set; }
        [Column("APELLIDO")]
        public string Apellido { get; set; }
        [Column("ESPECIALIDAD")]
        public string Especialidad { get; set; }
        [Column("SALARIO")]
        public int Salario { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
    }
}

MVCDoctoresCasa/Models/ErrorViewModel.cs
using System;

namespace MVCDoctoresCasa.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVCDoctoresCasa/Controllers/DoctoresController.cs
using ApiDoctoresPruebaCasa.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVCDoctoresCasa.Service;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace MVCDoctoresCasa.Controllers
{
    public class DoctoresController : Controller
    {
        private ServiceDoctores service;
        private ServiceS3 bucketService;

        public DoctoresController(ServiceDoctores service,ServiceS3 bucketService)
        {
            this.service = service;
            this.bucketService = bucketService;
        }

        public async Task<IActionResult> IndexDoctores()
        {
            List<Doctor> doctores = await this.service.GetDoctoresAsync();
            return View(doctores);
        }

        public async Task<IActionResult> GetDoctor(string id)
        {
            Doctor doc = await this.service.FindDoctor(id);
            return View(doc);
        }

        public IActionResult CreateDoctor()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateDoctor(string IdDoctor, string IdHospital, string Apellido, string Especialidad, string Salario, IFormFile Imagen)
        {
            string extension = Imagen.FileName.Split(".")[1];
            string fileName = IdDoctor.Trim() + "." + extension;
            using (Stream stream = Imagen.OpenReadStream())
            {
                await this.bucketService.UploadFileAsync(stream, fileName);
            }

            await this.service.InsertDoctorAsync(IdDoctor, IdHospital, Apellido, Especialidad, int.Parse(Salario), fileName);
            return RedirectToAction("IndexDoctores");
        }

        public async Task<IActionResult> DeleteDoctor(string id)
        {
            Doctor doc = await this.service.FindDoctor(id);
            await this.bucketService.DeleteFileAsync(doc.Imagen);
            await this.service.DeleteDoctor(id);
            return RedirectToAction("IndexDoctores");
        }
    }
}

MVCDoctoresCasa/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MVCDoctoresCasa.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MVCDoctoresCasa.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVCDoctoresCasa/Views/Doctores/CreateDoctor.cshtml
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Doctor</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" enctype="multipart/form-data">
            <div class="form-group">
                <label class="control-label">IdDoctor</label>
                <input name="IdDoctor" type="text" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">IdHospital</label>
                <input name="IdHospital" type="text" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Apellido</label>
                <input name="Apellido" type="text" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Especialidad</label>
                <input name="Especialidad" type="text" class="form-control" />
            </div>
            <div class="form-group">
                <label class="control-label">Salario</label>
                <input name="Salario" type="text" class="form-control" />
            </div>
            <div class="form-group">
                <label class="form-group">Imagen</label>
                <input name="Imagen" type="file" class="form-control" />
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

MVCDoctoresCasa/Views/Doctores/GetDoctor.cshtml
@model ApiDoctoresPruebaCasa.Models.Doctor

@{
    ViewData["Title"] = "GetDoctor";
}

<h1>GetDoctor</h1>

<div>
    <h4>Doctor</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cod_Hospital)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cod_Hospital)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NumDoctor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NumDoctor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Apellido)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Especialidad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Especialidad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Salario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Salario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Imagen)
        </dt>
        <dd class = "col-sm-10">
            <img src="https://bucketpruebascasa.s3.amazonaws.com/@Model.Imagen" style="width:100px;height:150px" />
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

MVCDoctoresCasa/Views/Doctores/IndexDoctores.cshtml
@model IEnumerable<ApiDoctoresPruebaCasa.Models.Doctor>

@{
    ViewData["Title"] = "IndexDoctores";
}

<h1>IndexDoctores</h1>

<p>
    <a asp-action="CreateDoctor" class="btn btn-success">New Doctor</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Cod_Hospital)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NumDoctor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Apellido)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Especialidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Imagen)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Cod_Hospital)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NumDoctor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Especialidad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Salario)
            </td>
            <td>
                <img src="https://bucketpruebascasa.s3.amazonaws.com/@item.Imagen" style="width:100px;height:150px"/>
            </td>
            <td>
                <a asp-controller="Doctores" asp-action="GetDoctor" asp-route-id="@item.NumDoctor" class="btn btn-info">Detalles</a>
                <a asp-controller="Doctores" asp-action="DeleteDoctor" asp-route-id="@item.NumDoctor" class="btn btn-danger">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

MVCDoctoresCasa/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MVCDoctoresCasa/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVCDoctoresCasa</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVCDoctoresCasa</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Doctores" asp-action="IndexDoctores">Doctores</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MVCDoctoresCasa - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>